<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="11.11.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.9" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.14.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="10.0.1" />
		<PackageReference Include="IdentityModel" Version="7.0.0" />
		<PackageReference Include="automapper" Version="16.1.1" />
		<PackageReference Include="StackExchange.Redis" Version="2.8.41" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
	</ItemGroup>

  <ItemGroup>
    <Folder Include="Models\Domains\Auxiliaries\" />
    <Folder Include="Models\Domains\Entities\" />
    <Folder Include="Models\Domains\Parameters\" />
    <Folder Include="Models\Domains\Relationships\" />
    <Folder Include="Interfaces\Externals\" />
    <Folder Include="Interfaces\Internals\Auxiliaries\" />
    <Folder Include="Interfaces\Internals\Entities\" />
    <Folder Include="Interfaces\Internals\Relationships\" />
    <Folder Include="Interfaces\Internals\Parameters\" />
    <Folder Include="Services\Externals\" />
    <Folder Include="Services\Internals\Auxiliaries\" />
    <Folder Include="Services\Internals\Entities\" />
    <Folder Include="Services\Internals\Middlewares\" />
    <Folder Include="Services\Internals\Parameters\" />
    <Folder Include="Services\Internals\Relationships\" />
    <Folder Include="Validations\Externals\" />
    <Folder Include="Validations\Internals\Auxiliaries\" />
    <Folder Include="Validations\Internals\Entities\" />
    <Folder Include="Validations\Internals\Parameters\" />
  </ItemGroup>

</Project>
